Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -247,6 +247,16 @@ jobs:
     - name: Build and Upload to App Store
       run: |
         fastlane gym --project ./ios/Runner.xcodeproj --scheme Runner --export_method app-store --allowProvisioningUpdates --verbose || true  # Add verbose flag and allow failure
+
+        # Check if the .ipa file exists
+        if [ -f ./build/ios/ipa/Runner.ipa ]; then
+          echo "IPA file exists!"
+        else
+          echo "IPA file not found!"
+          exit 1
+        fi
+
+        # Upload the .ipa to App Store
         fastlane deliver --ipa ./build/ios/ipa/Runner.ipa --skip_screenshots --skip_metadata --force --api_key_path "$HOME/ios/AuthKey.json" --app_identifier ${{ secrets.APP_IDENTIFIER }} --verbose
       env:
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
