Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -264,7 +264,7 @@ jobs:
     - name: Build and Upload to App Store
       run: |
         export XCODE_XCCONFIG_FILE=""
-        fastlane gym --project ./ios/Runner.xcodeproj --scheme Runner --export_method app-store --allow-provisioning-updates --verbose # || true  Add verbose flag and allow failure
+        fastlane gym --project ./ios/Runner.xcodeproj --scheme Runner --export_method app-store --verbose # || true  Add verbose flag and allow failure
         ls -l ./build/ios/ipa/
 
         # Check if the .ipa file exists
@@ -276,7 +276,7 @@ jobs:
         fi
 
         # Upload the .ipa to App Store
-        fastlane deliver --ipa ./build/ios/ipa/Runner.ipa --skip_screenshots --skip_metadata --force --api_key_path "$HOME/ios/AuthKey.json" --app_identifier ${{ secrets.APP_IDENTIFIER }} --allow-provisioning-updates --verbose
+        fastlane deliver --ipa ./build/ios/ipa/Runner.ipa --skip_screenshots --skip_metadata --force --api_key_path "$HOME/ios/AuthKey.json" --app_identifier ${{ secrets.APP_IDENTIFIER }} --verbose
       env:
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
