Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -251,7 +251,7 @@ jobs:
         echo "API Key Path: $HOME/ios/AuthKey.json"
 
     - name: Fastlane match (Sign iOS app)
-      run: fastlane match appstore --git_url git@github.com:Arundevraj463/Kode_App.git --api_key_path "$HOME/ios/AuthKey.json" --app_identifier ${{ secrets.APP_IDENTIFIER }} --allowProvisioningUpdates
+      run: fastlane match appstore --git_url git@github.com:Arundevraj463/Kode_App.git --api_key_path "$HOME/ios/AuthKey.json" --app_identifier ${{ secrets.APP_IDENTIFIER }} --readonly false
       env:
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
@@ -262,7 +262,7 @@ jobs:
     - name: Build and Upload to App Store
       run: |
         export XCODE_XCCONFIG_FILE=""
-        fastlane gym --project ./ios/Runner.xcodeproj --scheme Runner --export_method app-store --allowProvisioningUpdates --verbose || true  # Add verbose flag and allow failure
+        fastlane gym --project ./ios/Runner.xcodeproj --scheme Runner --export_method app-store --allow-provisioning-updates --verbose || true  # Add verbose flag and allow failure
         ls -l ./build/ios/ipa/
 
         # Check if the .ipa file exists
@@ -274,7 +274,7 @@ jobs:
         fi
 
         # Upload the .ipa to App Store
-        fastlane deliver --ipa ./build/ios/ipa/Runner.ipa --skip_screenshots --skip_metadata --force --api_key_path "$HOME/ios/AuthKey.json" --app_identifier ${{ secrets.APP_IDENTIFIER }} --allowProvisioningUpdates --verbose
+        fastlane deliver --ipa ./build/ios/ipa/Runner.ipa --skip_screenshots --skip_metadata --force --api_key_path "$HOME/ios/AuthKey.json" --app_identifier ${{ secrets.APP_IDENTIFIER }} --allow-provisioning-updates --verbose
       env:
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
