Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -246,12 +246,14 @@ jobs:
 
     - name: Build and Upload to App Store
       run: |
-        fastlane gym --project ./ios/Runner.xcodeproj --scheme Runner --export_method app-store --verbose || true  # Add verbose flag and allow failure
+        fastlane gym --project ./ios/Runner.xcodeproj --scheme Runner --export_method app-store --allowProvisioningUpdates --verbose || true  # Add verbose flag and allow failure
         fastlane deliver --ipa ./build/ios/ipa/Runner.ipa --skip_screenshots --skip_metadata --force --api_key_path "$HOME/ios/AuthKey.json" --app_identifier ${{ secrets.APP_IDENTIFIER }} --verbose
       env:
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
+        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
     
     - name: Clean up certificate repo
       run: rm -rf ./kode_app_cert_repo
